/**
 * Auto-generated database type aliases
 * Generated from: database.types.gen.ts
 * Generated at: 2025-08-05T20:18:34.390Z
 * 
 * DO NOT EDIT THIS FILE DIRECTLY
 * Run 'pnpm gen:types' to regenerate
 */

import type { Tables, TablesInsert, TablesUpdate } from './database.types.gen';

// Plan-related types
export type PlanExercises = Tables<'plan_exercises'>;
export type PlanExercisesInsert = TablesInsert<'plan_exercises'>;
export type PlanExercisesUpdate = TablesUpdate<'plan_exercises'>;

export type Plans = Tables<'plans'>;
export type PlansInsert = TablesInsert<'plans'>;
export type PlansUpdate = TablesUpdate<'plans'>;

// Exercise-related types
export type ExerciseMovementPatterns = Tables<'exercise_movement_patterns'>;
export type ExerciseMovementPatternsInsert = TablesInsert<'exercise_movement_patterns'>;
export type ExerciseMovementPatternsUpdate = TablesUpdate<'exercise_movement_patterns'>;

export type ExerciseMuscles = Tables<'exercise_muscles'>;
export type ExerciseMusclesInsert = TablesInsert<'exercise_muscles'>;
export type ExerciseMusclesUpdate = TablesUpdate<'exercise_muscles'>;

export type ExerciseRelationships = Tables<'exercise_relationships'>;
export type ExerciseRelationshipsInsert = TablesInsert<'exercise_relationships'>;
export type ExerciseRelationshipsUpdate = TablesUpdate<'exercise_relationships'>;

export type ExerciseTrainingStyles = Tables<'exercise_training_styles'>;
export type ExerciseTrainingStylesInsert = TablesInsert<'exercise_training_styles'>;
export type ExerciseTrainingStylesUpdate = TablesUpdate<'exercise_training_styles'>;

export type Exercises = Tables<'exercises'>;
export type ExercisesInsert = TablesInsert<'exercises'>;
export type ExercisesUpdate = TablesUpdate<'exercises'>;

// User/Profile types
export type Profiles = Tables<'profiles'>;
export type ProfilesInsert = TablesInsert<'profiles'>;
export type ProfilesUpdate = TablesUpdate<'profiles'>;

// Workout-related types
export type Sets = Tables<'sets'>;
export type SetsInsert = TablesInsert<'sets'>;
export type SetsUpdate = TablesUpdate<'sets'>;

export type WorkoutSessions = Tables<'workout_sessions'>;
export type WorkoutSessionsInsert = TablesInsert<'workout_sessions'>;
export type WorkoutSessionsUpdate = TablesUpdate<'workout_sessions'>;

// Chat/Memory types
export type Conversations = Tables<'conversations'>;
export type ConversationsInsert = TablesInsert<'conversations'>;
export type ConversationsUpdate = TablesUpdate<'conversations'>;

export type Memories = Tables<'memories'>;
export type MemoriesInsert = TablesInsert<'memories'>;
export type MemoriesUpdate = TablesUpdate<'memories'>;

// Reference data types
export type EquipmentTypes = Tables<'equipment_types'>;
export type EquipmentTypesInsert = TablesInsert<'equipment_types'>;
export type EquipmentTypesUpdate = TablesUpdate<'equipment_types'>;

export type MovementPatterns = Tables<'movement_patterns'>;
export type MovementPatternsInsert = TablesInsert<'movement_patterns'>;
export type MovementPatternsUpdate = TablesUpdate<'movement_patterns'>;

export type MuscleGroups = Tables<'muscle_groups'>;
export type MuscleGroupsInsert = TablesInsert<'muscle_groups'>;
export type MuscleGroupsUpdate = TablesUpdate<'muscle_groups'>;

export type TrainingStyles = Tables<'training_styles'>;
export type TrainingStylesInsert = TablesInsert<'training_styles'>;
export type TrainingStylesUpdate = TablesUpdate<'training_styles'>;

/**
 * Type guards to check if a value is of a specific database type
 */

export const isPlan = (value: unknown): value is Plans => {
  return (
    typeof value === 'object' &&
    value !== null &&
    'id' in value && 'name' in value && 'user_id' in value
  );
};

export const isExercis = (value: unknown): value is Exercises => {
  return (
    typeof value === 'object' &&
    value !== null &&
    'id' in value && 'name' in value && 'exercise_category' in value
  );
};

export const isProfil = (value: unknown): value is Profiles => {
  return (
    typeof value === 'object' &&
    value !== null &&
    'id' in value && 'username' in value
  );
};

export const isWorkoutSession = (value: unknown): value is WorkoutSessions => {
  return (
    typeof value === 'object' &&
    value !== null &&
    'id' in value && 'user_id' in value && 'started_at' in value
  );
};
