/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User Info
         * @description Get current authenticated user information.
         *
         *     Requires a valid JWT token in the Authorization header.
         */
        get: operations["get_current_user_info_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/public": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Public Endpoint
         * @description Public endpoint with optional authentication.
         *
         *     Returns different messages based on authentication status.
         */
        get: operations["public_endpoint_api_v1_auth_public_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user's workout plans
         * @description Retrieve a paginated list of the authenticated user's workout plans.
         *
         *     Returns a paginated list of plans filtered by the authenticated user's ID (via RLS).
         *     Plans are sorted by updated_at DESC to show most recently modified plans first.
         *     If no plans exist for the user, returns an empty array.
         *
         *     Args:
         *         limit: Maximum number of plans to return (1-100, default: 20)
         *         offset: Number of plans to skip for pagination (default: 0)
         *         jwt_payload: The authenticated user's JWT payload
         *         supabase: The Supabase client instance
         *
         *     Returns:
         *         PlanListResponseModel containing the plans array and pagination metadata
         *
         *     Raises:
         *         HTTPException: If plan retrieval fails due to database errors
         */
        get: operations["get_plans_api_v1_plans__get"];
        put?: never;
        /**
         * Create a new workout plan
         * @description Create a new workout plan.
         *
         *     Creates a new workout plan for the authenticated user with the provided details.
         *     The plan will be assigned a unique ID and version number 1.
         *
         *     Args:
         *         plan_data: The plan creation data
         *         jwt_payload: The authenticated user's JWT payload
         *         supabase: The Supabase client instance
         *
         *     Returns:
         *         The created plan with all database-generated fields
         *
         *     Raises:
         *         HTTPException: If plan creation fails due to validation or database errors
         */
        post: operations["create_plan_api_v1_plans__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a specific workout plan by ID
         * @description Retrieve a specific workout plan by its ID.
         *
         *     Returns the detailed plan data for the specified plan_id. Access is controlled
         *     by RLS policies - users can only access their own plans unless the plan is public.
         *     Public plans (is_public=true) can be viewed by anyone, including unauthenticated users.
         *
         *     Args:
         *         plan_id: The UUID of the plan to retrieve
         *         jwt_payload: Optional JWT payload - required for private plans, optional for public
         *         supabase: The Supabase client instance
         *
         *     Returns:
         *         PlanResponseModel containing the plan details
         *
         *     Raises:
         *         HTTPException:
         *             - 404 if plan doesn't exist or user lacks permission
         *             - 500 if retrieval fails due to database errors
         */
        get: operations["get_plan_by_id_api_v1_plans__plan_id__get"];
        /**
         * Update a workout plan (creates new version)
         * @description Update a workout plan by creating a new version.
         *
         *     Creates a new version of the specified plan with the provided updates.
         *     The original plan remains unchanged (immutable versioning). Only the plan owner
         *     can update their plans, and only active versions can be updated.
         *
         *     Version Management:
         *     - Increments version_number from the current version
         *     - Sets parent_plan_id to maintain version history
         *     - Marks the current version as inactive (is_active=false)
         *     - Marks the new version as active (is_active=true)
         *
         *     Args:
         *         plan_id: The UUID of the plan to update
         *         plan_update: The partial update data
         *         jwt_payload: The authenticated user's JWT payload
         *         supabase: The Supabase client instance
         *
         *     Returns:
         *         The newly created plan version with updated fields
         *
         *     Raises:
         *         HTTPException:
         *             - 400 if trying to update an inactive version or no changes provided
         *             - 403 if user doesn't own the plan
         *             - 404 if plan doesn't exist
         *             - 409 if version conflict occurs
         *             - 500 if update fails due to database errors
         */
        put: operations["update_plan_api_v1_plans__plan_id__put"];
        post?: never;
        /**
         * Soft delete a workout plan
         * @description Soft delete a workout plan.
         *
         *     Performs a soft delete by setting the deleted_at timestamp. Only the plan owner
         *     can delete their plans. Plans with active workout sessions cannot be deleted.
         *     The plan and all its versions will be marked as deleted.
         *
         *     Args:
         *         plan_id: The UUID of the plan to delete
         *         jwt_payload: The authenticated user's JWT payload
         *         supabase: The Supabase client instance
         *
         *     Returns:
         *         None (204 No Content on success)
         *
         *     Raises:
         *         HTTPException:
         *             - 400 if plan has active workout sessions
         *             - 403 if user doesn't own the plan
         *             - 404 if plan doesn't exist or is already deleted
         *             - 500 if deletion fails due to database errors
         */
        delete: operations["delete_plan_api_v1_plans__plan_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * DifficultyLevel
         * @description Workout plan difficulty levels.
         *
         *     Used to categorize plans by required experience and fitness level.
         * @enum {string}
         */
        DifficultyLevel: "beginner" | "intermediate" | "advanced";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PaginatedResponse[PlanResponseModel] */
        PaginatedResponse_PlanResponseModel_: {
            /** Items */
            items: components["schemas"]["PlanResponseModel"][];
            /** Page */
            page: number;
            /** Per Page */
            per_page: number;
            /** Total */
            total: number;
        };
        /**
         * PlanCreateModel
         * @description Model for creating a new workout plan.
         */
        PlanCreateModel: {
            /** Days Per Week */
            days_per_week?: number | null;
            /** Description */
            description?: string | null;
            difficulty_level?: components["schemas"]["DifficultyLevel"] | null;
            /** Duration Weeks */
            duration_weeks?: number | null;
            /** Goal */
            goal?: string | null;
            /**
             * Is Public
             * @default false
             */
            is_public: boolean;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Name */
            name: string;
            training_style: components["schemas"]["TrainingStyle"];
        };
        /**
         * PlanResponseModel
         * @description Model for workout plan API responses.
         */
        PlanResponseModel: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Days Per Week */
            days_per_week: number | null;
            /** Description */
            description: string | null;
            /** Difficulty Level */
            difficulty_level: string | null;
            /** Duration Weeks */
            duration_weeks: number | null;
            /** Goal */
            goal: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Public */
            is_public: boolean;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Name */
            name: string;
            /** Training Style */
            training_style: string;
        };
        /**
         * PlanUpdateModel
         * @description Model for updating an existing workout plan.
         */
        PlanUpdateModel: {
            /** Days Per Week */
            days_per_week?: number | null;
            /** Description */
            description?: string | null;
            difficulty_level?: components["schemas"]["DifficultyLevel"] | null;
            /** Duration Weeks */
            duration_weeks?: number | null;
            /** Goal */
            goal?: string | null;
            /** Is Public */
            is_public?: boolean | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
            /** Name */
            name?: string | null;
            training_style?: components["schemas"]["TrainingStyle"] | null;
        };
        /**
         * TrainingStyle
         * @description Training styles matching the database training_styles reference table.
         *
         *     These values are seeded in the database and should remain synchronized
         *     with supabase/seeds/01_reference_seed.sql.
         * @enum {string}
         */
        TrainingStyle: "powerlifting" | "bodybuilding" | "powerbuilding" | "general_fitness" | "athletic_performance";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_current_user_info_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    public_endpoint_api_v1_auth_public_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_plans_api_v1_plans__get: {
        parameters: {
            query?: {
                /** @description Maximum number of plans to return (1-100) */
                limit?: number;
                /** @description Number of plans to skip for pagination */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of plans retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_PlanResponseModel_"];
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "detail": "Not authenticated"
                     *     } */
                    "application/json": unknown;
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "detail": [
                     *         {
                     *           "loc": [
                     *             "query",
                     *             "limit"
                     *           ],
                     *           "msg": "ensure this value is greater than 0",
                     *           "type": "value_error.number.not_gt"
                     *         }
                     *       ]
                     *     } */
                    "application/json": unknown;
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "detail": "Failed to retrieve plans"
                     *     } */
                    "application/json": unknown;
                };
            };
        };
    };
    create_plan_api_v1_plans__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanCreateModel"];
            };
        };
        responses: {
            /** @description Plan created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResponseModel"];
                };
            };
            /** @description Invalid input data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "detail": "Plan name cannot be empty or only whitespace"
                     *     } */
                    "application/json": unknown;
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "detail": "Not authenticated"
                     *     } */
                    "application/json": unknown;
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "detail": [
                     *         {
                     *           "loc": [
                     *             "body",
                     *             "training_style"
                     *           ],
                     *           "msg": "Invalid training style",
                     *           "type": "value_error"
                     *         }
                     *       ]
                     *     } */
                    "application/json": unknown;
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "detail": "Failed to create plan"
                     *     } */
                    "application/json": unknown;
                };
            };
        };
    };
    get_plan_by_id_api_v1_plans__plan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plan retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResponseModel"];
                };
            };
            /** @description Plan not found or access denied */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "detail": "Plan not found"
                     *     } */
                    "application/json": unknown;
                };
            };
            /** @description Invalid plan ID format */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "detail": [
                     *         {
                     *           "loc": [
                     *             "path",
                     *             "plan_id"
                     *           ],
                     *           "msg": "value is not a valid uuid",
                     *           "type": "type_error.uuid"
                     *         }
                     *       ]
                     *     } */
                    "application/json": unknown;
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "detail": "Failed to retrieve plan"
                     *     } */
                    "application/json": unknown;
                };
            };
        };
    };
    update_plan_api_v1_plans__plan_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanUpdateModel"];
            };
        };
        responses: {
            /** @description Plan updated successfully (new version created) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResponseModel"];
                };
            };
            /** @description Invalid update request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "detail": "Not authenticated"
                     *     } */
                    "application/json": unknown;
                };
            };
            /** @description User does not own this plan */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "detail": "You do not have permission to update this plan"
                     *     } */
                    "application/json": unknown;
                };
            };
            /** @description Plan not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "detail": "Plan not found"
                     *     } */
                    "application/json": unknown;
                };
            };
            /** @description Version conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "detail": "A newer version of this plan already exists"
                     *     } */
                    "application/json": unknown;
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "detail": [
                     *         {
                     *           "loc": [
                     *             "body",
                     *             "duration_weeks"
                     *           ],
                     *           "msg": "ensure this value is greater than 0",
                     *           "type": "value_error.number.not_gt"
                     *         }
                     *       ]
                     *     } */
                    "application/json": unknown;
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "detail": "Failed to update plan"
                     *     } */
                    "application/json": unknown;
                };
            };
        };
    };
    delete_plan_api_v1_plans__plan_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plan deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Cannot delete plan with active workout sessions */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "detail": "Cannot delete plan - it has active workout sessions"
                     *     } */
                    "application/json": unknown;
                };
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "detail": "Not authenticated"
                     *     } */
                    "application/json": unknown;
                };
            };
            /** @description User does not own this plan */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "detail": "You do not have permission to delete this plan"
                     *     } */
                    "application/json": unknown;
                };
            };
            /** @description Plan not found or already deleted */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "detail": "Plan not found"
                     *     } */
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {
                     *       "detail": "Failed to delete plan"
                     *     } */
                    "application/json": unknown;
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
