#!/usr/bin/env node

/**
 * Script to generate TypeScript type aliases from Supabase generated types
 * 
 * This script reads the generated database.types.gen.ts file and creates
 * convenient type aliases for all database tables.
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

// Get __dirname equivalent in ES modules
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Convert snake_case to PascalCase
function toPascalCase(str: string): string {
  return str
    .split('_')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join('');
}

// Main generation function
function generateDatabaseTypes() {
  const projectRoot = path.resolve(__dirname, '..');
  const inputFile = path.join(projectRoot, 'src', 'types', 'database.types.gen.ts');
  const outputFile = path.join(projectRoot, 'src', 'types', 'api.types.gen.ts');

  // Read the generated database types file
  let content: string;
  try {
    content = fs.readFileSync(inputFile, 'utf-8');
  } catch (error) {
    console.error('Error reading database.types.gen.ts:', error);
    console.error('Make sure to run "supabase gen types typescript" first');
    process.exit(1);
  }

  // Find all table definitions by looking for the pattern "tablename: { Row:"
  // This is more reliable than trying to parse the nested structure
  const tableNames: string[] = [];
  
  // Look for all occurrences of table definitions
  // They follow the pattern: word: { Row: {
  const tableMatches = content.matchAll(/(\w+):\s*\{\s*Row:\s*\{/g);
  
  for (const match of tableMatches) {
    // Filter out any non-table matches
    const tableName = match[1];
    // Skip if it's a TypeScript utility type or other non-table
    if (!tableName.includes('Table') && !tableName.includes('Type') && tableName !== 'Row') {
      tableNames.push(tableName);
    }
  }

  if (tableNames.length === 0) {
    console.error('No tables found in database.types.gen.ts');
    console.error('Make sure the file contains table definitions with Row properties');
    process.exit(1);
  }

  console.log(`Found ${tableNames.length} tables:`, tableNames);

  // Generate the type aliases
  const header = `/**
 * Auto-generated database type aliases
 * Generated from: database.types.gen.ts
 * Generated at: ${new Date().toISOString()}
 * 
 * DO NOT EDIT THIS FILE DIRECTLY
 * Run 'pnpm generate:db-types' to regenerate
 */

import type { Tables, TablesInsert, TablesUpdate } from './database.types.gen';

`;

  // Group tables by category for better organization
  // Use Set to track which tables have been categorized
  const categorized = new Set<string>();
  
  const planTables = tableNames.filter(t => {
    if (t.includes('plan') && !categorized.has(t)) {
      categorized.add(t);
      return true;
    }
    return false;
  });
  
  const exerciseTables = tableNames.filter(t => {
    if ((t.includes('exercise') || t === 'exercises') && !categorized.has(t)) {
      categorized.add(t);
      return true;
    }
    return false;
  });
  
  const workoutTables = tableNames.filter(t => {
    if ((t.includes('workout') || t === 'sets') && !categorized.has(t)) {
      categorized.add(t);
      return true;
    }
    return false;
  });
  
  const userTables = tableNames.filter(t => {
    if ((t.includes('profile') || t === 'users') && !categorized.has(t)) {
      categorized.add(t);
      return true;
    }
    return false;
  });
  
  const chatTables = tableNames.filter(t => {
    if ((t.includes('conversation') || t.includes('memor')) && !categorized.has(t)) {
      categorized.add(t);
      return true;
    }
    return false;
  });
  
  const referenceTables = tableNames.filter(t => !categorized.has(t));

  let output = header;

  // Helper function to generate type exports for a group
  const generateTypeExports = (tables: string[], comment: string) => {
    if (tables.length === 0) return '';
    
    let result = `// ${comment}\n`;
    for (const table of tables) {
      const typeName = toPascalCase(table);
      result += `export type ${typeName} = Tables<'${table}'>;\n`;
      result += `export type ${typeName}Insert = TablesInsert<'${table}'>;\n`;
      result += `export type ${typeName}Update = TablesUpdate<'${table}'>;\n\n`;
    }
    return result;
  };

  // Generate organized type exports
  output += generateTypeExports(planTables, 'Plan-related types');
  output += generateTypeExports(exerciseTables, 'Exercise-related types');
  output += generateTypeExports(userTables, 'User/Profile types');
  output += generateTypeExports(workoutTables, 'Workout-related types');
  output += generateTypeExports(chatTables, 'Chat/Memory types');
  output += generateTypeExports(referenceTables, 'Reference data types');

  // Add type guards for the most commonly used types
  output += `/**
 * Type guards to check if a value is of a specific database type
 */
`;

  // Generate type guards for main entities
  const mainEntities = ['plans', 'exercises', 'profiles', 'workout_sessions'];
  for (const entity of mainEntities) {
    if (tableNames.includes(entity)) {
      const typeName = toPascalCase(entity);
      const singular = entity.endsWith('es') ? entity.slice(0, -2) : entity.slice(0, -1);
      const guardName = `is${toPascalCase(singular)}`;
      
      // Determine key fields based on entity type
      let keyFields = `'id' in value`;
      if (entity === 'plans') {
        keyFields = `'id' in value && 'name' in value && 'user_id' in value`;
      } else if (entity === 'exercises') {
        keyFields = `'id' in value && 'name' in value && 'exercise_category' in value`;
      } else if (entity === 'profiles') {
        keyFields = `'id' in value && 'username' in value`;
      } else if (entity === 'workout_sessions') {
        keyFields = `'id' in value && 'user_id' in value && 'started_at' in value`;
      }
      
      output += `
export const ${guardName} = (value: unknown): value is ${typeName} => {
  return (
    typeof value === 'object' &&
    value !== null &&
    ${keyFields}
  );
};
`;
    }
  }

  // Write the output file
  try {
    fs.writeFileSync(outputFile, output);
    console.log(`✅ Successfully generated ${outputFile}`);
    console.log(`📦 Generated ${tableNames.length} table types with Insert and Update variants`);
  } catch (error) {
    console.error('Error writing output file:', error);
    process.exit(1);
  }
}

// Run the generation
generateDatabaseTypes();